### ISSUE TITLE
Usage / Documentation

### ISSUE THREAD

**Issue by Claudio-Chies** [ARK-Electronics/omnitrack#6]
With the existing instruction i'm not able to make it work.
i opened a PR (https://github.com/ARK-Electronics/tracktor-beam/pull/5)  to add installation instruction with which I'm able to launch all nodes without error messages.
some commands like ` ros2 run aruco_tracker aruco_tracker `  were not documented but used in the you tube video, so are they needed or not?

for me it always goes into fallback mode in px4.

**Comment by dakejahl** [comment]
The tutorial is based on this branch https://github.com/ARK-Electronics/tracktor-beam/tree/aruco_tutorial

Did you try this?
